### ISSUE TITLE
Transaction example?

### ISSUE THREAD

**Issue by fr3fou** [Fs02/go-todo-backend#2]
One issue that I've had to deal with when using any go sql library is how to handle transactions, especially among different repos. I have a longer write up that explains the issue right here https://github.com/upper/db/issues/543

I'd be very glad if you could provide an example how rel could solve this issue

**Comment by Fs02** [comment]
sure, give me time to think about some a real/study case.
any suggestion as long as it's simple (for example purpose) and still related to todo app is also welcomed :D

**Comment by Fs02** [comment]
Btw, if you are not aware, since v0.5.0 REL uses context to manage transaction connection, so there's no need to pass connection/repo object as function argument when calling another function within transaction, using context also makes dealing with nested transaction across different function calls seamless.

see this PR: https://github.com/Fs02/rel/pull/76
and updated transaction doc: https://fs02.github.io/rel/#/transactions

**Comment by fr3fou** [comment]
> sure, give me time to think about some a real/study case.
> any suggestion as long as it's simple (for example purpose) and still related to todo app is also welcomed :D

well let's pretend that a user has many todos and also has a score based on how many todos they have completed; you could both mark a todo as completed and increment their points inside a transaction for example

**Comment by Fs02** [comment]
Hi @fr3fou, check this PR https://github.com/Fs02/go-todo-backend/pull/3 for transaction demo, what do you think?

**Comment by fr3fou** [comment]
LGTM!
