### ISSUE TITLE
What's the reasoning for using a migration solution in ruby?

### ISSUE THREAD

**Issue by fr3fou** [Fs02/go-todo-backend#4]
Wouldn't it be cleaner to have the migrations in go as well?

**Comment by Fs02** [comment]
actually the reason is written in readme inside the folder: https://github.com/Fs02/go-todo-backend/tree/master/db

I can't find any golang migration library that have feature what I need, for example solution like [migrate](https://github.com/golang-migrate/migrate) can only do up and down migration, but can't handle migration that is inserted in the middle, so working with multiple people and multiple branch is painful, have to update migration version/rollback every time a new branch merged. https://github.com/golang-migrate/migrate/issues/299
It's also doesn't play well with failed migration script (have to fix the schema version table manually if this happen).

Solution like [kamimai](https://github.com/eure/kamimai/) works with the above case, but only support mysql.

**Comment by Fs02** [comment]
Closing this issue because migration is now done using go as well, Thanks 😄
